---
author: "Noreen Mayat"
title: "project2"
output: html_document
date: "2023-09-30"
---

Make sure to install all packages below before running any code; I installed them by running: 
```{r}
# install.packages('package') for each package listed.
```

Set ur directory. I set mine running this in the console:
```{r}
#setwd('Desktop/GitHub/ads-fall2023-project2-group2/doc/')
```

Load libraries
```{r load_libraries, warning=FALSE, include=FALSE, echo=FALSE}
library(dplyr)
library(stats)
library(ggplot2)
library(ggrepel)
library(udpipe)
library(plotly)
library(plyr)
```

Read in data
```{r}
pathfile <- '../data/HousingAssistanceOwners.csv'
owner_data <- read.csv(pathfile)

pathfile_2 <- '../data/HousingAssistanceRenters.csv'
renter_data <- read.csv(pathfile_2)

pathfile_3 <- '../data/owners_summary_state_groupby.csv'
state_incident_data <- read.csv(pathfile_3)
```


```{r}
# calculate sum of each 
x1 <- sum(owner_data$approvedBetween1And10000)
x2 <- sum(owner_data$approvedBetween10001And25000)
x3 <- sum(owner_data$approvedBetween25001AndMax)
```


```{r}
jpeg(filename="figs/owners_pie_chart.jpg",width=480,height=480)
slices <- c(x1, x2, x3)
lbls <- c("1-10000", "10001-25000", "25001-Max")
pie(slices, labels = lbls, col=rainbow(length(lbls)), main="Pie Chart for Owners Approved Amounts")
dev.off()
```


```{r}
y1 <- sum(renter_data$approvedBetween1And10000)
y2 <- sum(renter_data$approvedBetween10001And25000)
y3 <- sum(renter_data$approvedBetween25001AndMax)
```


```{r}
jpeg(filename="figs/renters_pie_chart.jpg",width=480,height=480)
slices <- c(y1, y2, y3)
lbls <- c("1-10000", "10001-25000", "25001-Max")
pie(slices, labels = lbls, col=rainbow(length(lbls)), main="Pie Chart for Renters Approved Amounts")
dev.off()
```


```{r}
slices <- c(x1, x2, x3)
lbls <- c("1-10000", "10001-25000", "25001-Max")
pie(slices, labels = lbls, col=rainbow(length(lbls)), main="Pie Chart for Owners Approved Amounts")
```


```{r}
# create data quantiles
state_incident_data$percentile_damage = rank(state_incident_data$total_damage_sum)/nrow(state_incident_data)*100
state_incident_data$percentile_amt = rank(state_incident_data$total_approved_amount_sum)/nrow(state_incident_data)*100

# calculating empirical distribution of total damage/total approved amount based on state and incident type
empirical_dist <- function(df, incident, state, amount, damage){
  data <- df %>% 
    filter(incidentType == incident, state == state, percentile_amt <= amount, percentile_damage <= damage)
    if (dim(data)[1] == 0) {
    print("No Data")
    break
}
  ecdf_func <- ecdf(data$total_damage_sum)
  plot(ecdf_func, xlab='Damage', ylab="Approved Amount",  
     main="Empirical Cumulative Distribution Function Plot for Approved Amounts/Damage")
}
```





